export const ICON_NAME = {
    BUSCA_CONTORNADO: 'search-outline',
    CARRINHO_CONTORNADO: 'cart-outline',
    PAPEL_LISTA_CONTORNADO: 'newspaper-outline',
    ADICIONAR_PESSOA_CONTORNADO: 'person-add-outline',
    LOCALIZACAO: 'location-outline',
    CAIXA_ARQUIVO_CONTORNADO: 'archive-outline',
    CODIGO_BARRA_CONTORNADO: 'barcode-outline',
    OBRA_CONTORNADO: 'construct-outline',
    CHECK_CONTORNADO: 'bag-check-outline',
    FILTRAR_CONTORNADO: 'filter-circle-outline',
    ESTATISTICA_CONTORNADO: 'stats-chart-outline',
    LISTA_CONTORNADO: 'list-outline',
    CESTA_CONTORNADO: 'basket-outline',
    ADICIONAR_CONTORNADO: 'add-outline',
    VOLTAR_CONTORNADO: 'arrow-back-outline',
    FLECHA_ESQUERDA: 'chevron-back-outline',
    FLECHA_DIRETA: 'chevron-forward-outline',
    FLECHA_CIMA: 'chevron-up-outline',
    FLECHA_BAIXO: 'chevron-down-outline',
    LIXEIRA: 'trash-outline',
    CHECK: 'save-outline',
    TRISTE: 'sad-outline',
    ENVIAR: 'send-outline',
    CHAT: 'chatbox-ellipses-outline',
    ANEXO: 'attach-outline',
    BUG_ERROR: 'bug-outline',
    SUCCESS: 'checkmark-outline',
    ALERT: 'alert-outline',
    IMAGE: 'image-outline',
    DOCUMENT: 'document-attach-outline',
    DOCUMENT_EMPTY: "document-outline",
    EDITAR: "create-outline",
    FECHAR: "close-circle-outline",
    CAMERA: "camera-outline",

}