
/**
 * INTERFACE RESPONSAVEL POR IDENTIFICAR QUAL FORMA DE PAGAMENTO
 * DEVE SER BUSCADA NA API
 */
export enum PaymentForm {
    VISTA = 0,
    DINHEIRO = 1,
    VALE_CREDITO = 2,
    VALE_PRESENTE = 3
}

