export interface IReqSave1201 {
    Id: string
    BB012_ZonaID: string
    BB012_AtividadeID: string
    BB012_LimiteCredito: number
    BB012_LimCreditoSecun: number
    BB012_LimiteCCredito: number
    BB012_DiaVenctoCartao: number
    BB012_ContaConvenio: string
    BB012_DiasPagtoConv: number
    BB012_PadraoBancoID: string
    BB012_BcoAgenciaConta: string
    BB012_Revenda: number
    BB012_Taxa_Administracao_Con: number
    BB012_Requisicao: number
    BB012_ContaContabil: string
    BB012_HistoricoContabilID: string
    BB012_ContratoCartao: number
    BB012_DataContratoCartao: string
    BB012_DtValidadeCartao: string
    BB012_ModalidadeCredCartao: string
    BB012_PercLimCredito: number
    BB012_PrazoEntregaFornec: number
    BB012_CondPagtoFornec: string
    BB012_NatOperacaoID: string
    BB012_CondPagtoID: string
    BB012_TextoNotaId: string
    BB012_Grau_Risco: string
    BB012_Classe_Credito: string
    BB012_DtValidCadastro: string
    BB012_Perc_ICMS: number
    BB012_CodgCategoria: string
    BB012_CategoriaID: string
    BB012_LimiteCredParcela: number
    BB012_Num_Ult_Fatura: number
    BB012_TotCompraCarnet: number
    BB012_Valor_Entrada: number
    BB012_Maior_Compra: number
    BB012_Menor_Compra: number
    BB012_TotDiasAtraso: number
    BB012_Maior_Atraso: number
    BB012_Menor_Atraso: number
    BB012_MediaDeAtraso: number
    BB012_MaiorSaldo: number
    BB012_NumCompras: number
    BB012_DtPrimCompra: string
    BB012_DtUltCompra: string
    BB012_VlrMaiorPagto: number
    BB012_NumPagtoDia: number
    BB012_NumPagtoAtraso: number
    BB012_SaldoDevedor: number
    BB012_SaldoPedido: number
    BB012_QtdTitProtestado: number
    BB012_UltProtesto: string
    BB012_QtdChqDevolvido: number
    BB012_UltChqDevolvido: string
    BB012_Convenio_ID: number
    BB012_TipoGeracao_ID: number
    BB012_SitEspecial_ID: number
    BB012_EntMtgRotaID: string
    BB012_VendaRotaID: string
    bb012_DiaVenctoID: string
    bb012_CodgBcoDebConta: string
}