name: Gerar pacote PV-Mobile
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente: dev ou prod'
        required: true
        default: 'prod'
      versionCode:
        description: 'Código de versão do aplicativo. Ex 6'
        required: true
        default: '1' 
      versionName:
        description: 'Nome da versão do aplicativo. Ex 0.2.2'
        required: true
        default: '0.1.0' 

env:
  NODE_VERSION: '20.x' 

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Modificando version.properties
        run: |
           sed -i 's/^TESTE=.*/TESTE=NOVOTEXTO/' version.properties


  


     
