name: Gerar pacote PV-Mobile aab

on:
  push:
    branches: [ "csprd" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'  # Versão do Node a ser usada

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Expo CLI
        run: npm install expo-cli --global

      - name: Install npm dependencies
        run: npm install

      - name: Give execute permission to gradlew
        run: chmod +x android/gradlew

      - name: Generate AAB
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: cs-pvmobile-0.1.0-aab
          path: android/app/build/outputs/apk/release/cs-pvmobile-0.1.0-aab

