name: Gerar pacote PV-Mobile
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente: dev ou prod'
        required: true
        default: 'prod'
      versionCode:
        description: 'Código de versão do aplicativo. Ex 6'
        required: true
        default: '1' 
      versionName:
        description: 'Nome da versão do aplicativo. Ex 0.2.2'
        required: true
        default: '0.1.0' 

env:
  NODE_VERSION: '20.x' 

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Modificando version.properties
        run: |
            echo "Original version.properties content:"
            cat version.properties
            
            
            sed -i 's/^TESTE=.*/TESTE=NOVOTEXTO/' version.properties || echo "No match found"
            
            
            echo "Updated version.properties content:"
            cat version.properties

            
      - name: Update version in app.json
        run: |
          NEW_VERSION="1.2.0"
          
          # Update the version field in app.json
          jq ".expo.version = \"$NEW_VERSION\"" app.json > temp.json && mv temp.json app.json

  


     
