name: Build and Deploy Android APK to AWS EC2

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'  # Versão do Node a ser usada

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Expo CLI
        run: npm install expo-cli --global

      - name: Install npm dependencies
        run: npm install

      - name: Give execute permission to gradlew
        run: chmod +x android/gradlew

      - name: Generate APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Download APK
#        uses: actions/download-artifact@v3
#        with:
#          name: app-release-apk
#          path: ./release

#      - name: Configure SSH Access
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.AWS_EC2_KEY_PAIR }}" > ~/.ssh/aws_ec2_key
#          chmod 600 ~/.ssh/aws_ec2_key
#          ssh-keyscan -H 44.193.189.111 >> ~/.ssh/known_hosts
#          echo "StrictHostKeyChecking no" > ~/.ssh/config

#      - name: Creating folder on EC2
#        run: |
#          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "mkdir -p /home/ubuntu/app"


#      - name: Upload APK to EC2
#        run: |
#          scp -i ~/.ssh/aws_ec2_key ./release/app-release.apk ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }}:/home/ubuntu/app/app-release.apk

#      - name: SSH into EC2 and deploy APK
#        run: |
#          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} << 'EOF'
#            mv /home/ubuntu/app/app-release.apk /var/www/myapp/app-release.apk
            # Adicione aqui outros comandos necessários para sua aplicação
#          EOF
