name: Gerar pacote PV-Mobile
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente: dev ou prod'
        required: true
        default: 'prod'
      versionCode:
        description: 'Código de versão do aplicativo. Ex 6'
        required: true
        default: '1' 
      versionName:
        description: 'Nome da versão do aplicativo. Ex 0.2.2'
        required: true
        default: '0.1.0' 

env:
  NODE_VERSION: '20.x' 

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Modificando version.properties
        run: |
            echo "Original version.properties content:"
            cat version.properties
            
            
            sed -i 's/^TESTE=.*/TESTE=NOVOTEXTO/' version.properties || echo "No match found"
            
            
            echo "Updated version.properties content:"
            cat version.properties

      - name: Commit changes
        run: |
          git config --local user.email "valter.gabriel@cs-consoft.com.br"  # Replace with your email
          git config --local user.name "valtecsgabriel"  # Replace with your name
          git add version.properties
          git commit -m "Update TESTE value in version.properties" || echo "No changes to commit"
          
      - name: Push changes
        run: git push

  


     
